[package]
name = "shire"
version = "0.1.0"
authors = ["Willow GHOST <ghostdevbusiness@gmail.com> (willow.sh)"]
description = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
reqwest = "0.11.18"
tokio = "1.30.0"
